dms.marketdata.upload-file.url=https://team.dms.mas.gov.sg/sites/SGS/_api/web/GetFolderByServerRelativeUrl('/sites/SGS/MMO/Change%20Requests/2022/02-SCRIPS%20and%20Refinitiv/Read%20Excel%20POC')/Files/Add(url='replacefilename',overwrite=true)
dms.marketdata.url=https://team.dms.mas.gov.sg/sites/SGS/_api/Web/GetFileByServerRelativeUrl('/sites/SGS/MMO/Change%20Requests/2022/02-SCRIPS%20and%20Refinitiv/Read%20Excel%20POC/replacefilename')/ListItemAllFields/ValidateUpdateListItem
dms.marketdata.data=Business_x0020_Functions=Foreign Exchange Operations|682c1576-0aec-4529-8a06-42f0931b13fc;Security_x0020_Classification=Restricted|86c47f45-3406-42c4-a9a0-f1318f859c90;ISF_x0020_Classification=Non-Sensitive;Document_x0020_Type=Adhoc Reports|4a3917d1-3169-4b21-8c13-33c20fd04709
dms.authentication.url=https://team.dms.mas.gov.sg/sites/SGS/_api/contextinfo
dms.domain=null
dms.userid=b_mddmo_dms_q
dms.password=WATERmelon2025@#qa
ssl.key-store=/mas_apps/amo/cert/ammo-client.jks
ssl.key-store-password=P@ssw0rd@mmo

logging.level.org.apache.hc=DEBUG